development:
  adapter: mysql
  encoding: utf8
  database: {{app_name}}_dev
  username: root
  password: 
test:
  adapter: mysql
  encoding: utf8
  database: {{app_name}}_test
  username: root
  password: